spring:
  application:
    name: test-liquibase

  datasource:
    url: jdbc:postgresql://localhost:5432/product_catalog
    username: product_user
    password: product_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
